//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Policy = new HashSet<Policy>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string login { get; set; }
    
        public virtual ICollection<Policy> Policy { get; set; }
    }
}
