//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredObject
    {
        public long policy_id { get; set; }
        public byte construction_type { get; set; }
        public short area { get; set; }
        public byte object_type { get; set; }
        public bool is_fire_alarm { get; set; }
        public bool is_burglary_alarm { get; set; }
        public short construction_year { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
