//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public long id { get; set; }
        public string number { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_tille { get; set; }
        public System.DateTime created_at { get; set; }
        public byte status { get; set; }
        public Nullable<decimal> premium { get; set; }
        public int holder_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual InsuredObject InsuredObject { get; set; }
    }
}
